# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "near"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "near_dbt"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  near:
    +re_data_monitored: true
    # +re_data_time_filter: block_timestamp
    # # Config indicated by + and applies to all files under models/example/
    # example:
    #   +materialized: view

sources:
  near:
    chainwalkers:
      near_blocks:
        +re_data_monitored: true
        +re_data_time_filter: ingested_at
      near_txs:
        +re_data_monitored: true
        +re_data_time_filter: ingested_at

tests:
  +severity: warn  # all tests

vars:
  re_data:save_test_history: true